### ISSUE TITLE
Timing code fix (millis till ready / "warmed up" in loop vs burst count)

### ISSUE THREAD

**Issue by kenchong48** [rrivirr/rriv#95]

**Comment by kenchong48** [comment]
Will use Ken's code for timing for now

**Comment by ZavenArra** [comment]
I don't understand what this issue is about right now, can you describe the problem?  We made some hack to get around something here?

**Comment by kenchong48** [comment]
I believe this was an issue of when is a sensor ready to take samples, vs when is it warmed up (how often/when do we check when it is warmed up), vs how often does a user want to take samples.  Across different sensors we could have wanting to take analog readings very fast, as compared to a sensor that can only give samples every 2 seconds

What I implemented only takes samples when the slowest sensor is ready to take readings, and does not log extra values in between that, I don't think this accounts for if all sensors are analog and can read continuously though.

The code for mixing and matching these speeds is something you said you would think through.

**Comment by ZavenArra** [comment]
Closing this issue as not specific enough.
